# Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
      - 
        AttributeName: ArtistId
        AttributeType: S
      - 
        AttributeName: Concert
        AttributeType: S
      - 
        AttributeName: TicketSales
        AttributeType: S
      KeySchema:
      -
        AttributeName: ArtistId
        KeyType: HASH
      -
        AttributeName: Concert
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: sample-table